In [1]:
import os
import pandas as pd
import numpy as np
import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html
import pandas as pd
import plotly.graph_objs as go
import plotly.express as px
import plotly.graph_objects as go

C:\Users\Maxim\AppData\Local\Temp/ipykernel_24856/2239549247.py:6: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
C:\Users\Maxim\AppData\Local\Temp/ipykernel_24856/2239549247.py:7: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html

In [2]:
confirmed_df = pd.read_csv("raw_data_files/confirmed_regions.csv")
deaths_df = pd.read_csv("raw_data_files/deaths_regions.csv")

In [3]:
deaths_df.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,1/19/22,1/20/22,1/21/22,ISO 3166-1 Alpha 3-Codes,Region Code,Region Name,Sub-region Code,Sub-region Name,Intermediate Region Code,Intermediate Region Name
0,#adm1+name,#country+name,#geo+lat,#geo+lon,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,#country+code,#region+main+code,#region+main+name,#region+sub+code,#region+sub+name,#region+intermediate+code,#region+intermediate+name
1,NaN,Afghanistan,33.93911,67.709953,0.0,0.0,0.0,0.0,0.0,0.0,...,7386.0,7386.0,7390.0,AFG,142,Asia,34,Southern Asia,NaN,NaN
2,NaN,Albania,41.1533,20.1683,0.0,0.0,0.0,0.0,0.0,0.0,...,3283.0,3286.0,3292.0,ALB,150,Europe,39,Southern Europe,NaN,NaN
3,NaN,Algeria,28.0339,1.6596,0.0,0.0,0.0,0.0,0.0,0.0,...,6443.0,6453.0,6468.0,DZA,2,Africa,15,Northern Africa,NaN,NaN
4,NaN,Andorra,42.5063,1.5218,0.0,0.0,0.0,0.0,0.0,0.0,...,142.0,144.0,144.0,AND,150,Europe,39,Southern Europe,NaN,NaN

In [4]:
#Removing first row
confirmed_df = confirmed_df.iloc[1: , :]
deaths_df = deaths_df.iloc[1: , :]

In [5]:
#Renaming columns
confirmed_df.rename(columns={'Country/Region': 'Country', 'Region Name': 'Continent', 'Sub-region Name': 'Region', 'Region Code': 'Continent Code', 'Sub-region Code': 'Region Code'},inplace=True)
deaths_df.rename(columns={'Country/Region': 'Country', 'Region Name': 'Continent', 'Sub-region Name': 'Region', 'Region Code': 'Continent Code', 'Sub-region Code': 'Region Code'},inplace=True)

In [6]:
#Removing unnecessary columns & grouping by Country
confirmed_df=confirmed_df.drop(columns=['Province/State', 'ISO 3166-1 Alpha 3-Codes', 'Intermediate Region Code', 'Intermediate Region Name'])

countries_confirmed_df=confirmed_df.groupby(['Country']).sum().copy()
countries_deaths_df=deaths_df.groupby(['Country']).sum().copy()

In [7]:
combined_df=pd.DataFrame()
combined_df['Confirmed']=countries_confirmed_df[countries_confirmed_df.columns[-1]]
combined_df['Deaths']=countries_deaths_df[countries_deaths_df.columns[-1]]

In [8]:
sorted_combined_df=combined_df.loc[:,["Confirmed","Deaths"]].sort_values("Confirmed",ascending=False)
sorted_combined_df['Country']=sorted_combined_df.index
combined_df.loc[:,["Confirmed","Deaths"]].sort_values("Confirmed",ascending=False).style.background_gradient(cmap='Blues',subset=["Confirmed"]).background_gradient(cmap='Reds',subset=["Deaths"]).background_gradient(cmap='Green',subset=["Recovered"])

KeyError: "None of [Index(['Recovered'], dtype='object')] are in the [columns]"

In [9]:
sorted = []
sorted.append(confirmed_df[0])
for i in range(len(confirmed_df.index)):
    

sorted_df = pd.DataFrame(data, columns=['A'])
    

sorted_df.head()

,Country,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,...,1/16/22,1/17/22,1/18/22,1/19/22,1/20/22,1/21/22,Continent Code,Continent,Region Code,Region
1,Afghanistan,33.93911,67.709953,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,158717.0,158826.0,158974.0,159070.0,159303.0,159516.0,142,Asia,34,Southern Asia
2,Albania,41.1533,20.1683,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,232637.0,233654.0,236486.0,239129.0,241512.0,244182.0,150,Europe,39,Southern Europe
3,Algeria,28.0339,1.6596,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,226057.0,226749.0,227559.0,228918.0,230470.0,232325.0,2,Africa,15,Northern Africa
4,Andorra,42.5063,1.5218,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,29888.0,29888.0,29888.0,29888.0,32201.0,33025.0,150,Europe,39,Southern Europe
5,Angola,-11.2027,17.8739,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,93694.0,93974.0,94275.0,94779.0,95220.0,95676.0,2,Africa,202,Sub-Saharan Africa